[package]
name = "groove-tui"
version = "0.2.5"
edition = "2024"
description = "A terminal guitar practice companion with metronome, tuner, and fretboard tools"
license = "MIT"
repository = "https://github.com/DiogoTeixeiraDEV/GrooveTui"
homepage = "https://github.com/DiogoTeixeiraDEV/GrooveTui"
readme = "README.md"
keywords = ["tui", "guitar", "metronome", "tuner"]
categories = ["command-line-interface"]

[dependencies]
# Interface (TUI)
ratatui = "0.29"
crossterm = "0.27"

# Áudio
rodio = "0.17"
cpal = "0.15"
libc = "0.2"

crossbeam-channel = "0.5"
pitch-detection = "0.3"


# Utilitários e Tratamento de Erros
anyhow = "1.0"

# Teoria Musical (para o futuro gerador de harmonias)
rust-music-theory = "0.3"
